player:
  score-topic: scores.topic

spring:
  application:
    name: demo-golf-service
  json:
    trusted-packages: "*"


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      enable-auto-commit: false
      max-poll-records: 10
      fetch-max-wait: 500
      max-partition-fetch-bytes: 1024 * 1024
      isolation-level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: batch
      batch-listener: true
      concurrency: 3

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432